### ISSUE TITLE
emonpi LCD gprs lib not in repo

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/emonpi#1]
I'm getting 
Traceback (most recent call last):
  File "/home/debian/emonpi/lcd/emonPiLCD.py", line 8, in <module>
    from  gprs_signal import get_gsm_signal_strength
ImportError: No module named gprs_signal

@Basazababo Where is this module?

**Comment by Basazababo** [comment]
here is the path: /home/debian/emonpi/lcd/gprs_signal.py

**Comment by jlark** [comment]
Let's merge this repo with the monpi repo. 
I would put all gprs related code under a gpre folder just like the lcd folder.

Also keep in mind to modify the import paths in the scripts and also emonpiLCD.py

**Comment by Basazababo** [comment]
Yeap,
Let me do that

**Comment by Basazababo** [comment]
Shutdown is not working,
it`s displaying the shutdown process but does not halt the system.
