### ISSUE TITLE
remove emonhub from the installation step

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/emonpi#29]
This will be downloaded automatically from the server going forward.

**Comment by Basazababo** [comment]
Do you mean that we need to change emonhub installation in emoncms9install script?

**Comment by jlark** [comment]
I believe this is done in the ansible scripts. No?

**Comment by Basazababo** [comment]
I think that Ansible script runs this emoncms9install, emonhub requirements and put there updated emonhub.conf file;
The current ansible scripts we have can not execute it alone, unless we modify it.

**Comment by jlark** [comment]
ok can you modify it so when a system is installed there is not config file under /home/debian/data/emonhub.conf

**Comment by Basazababo** [comment]
Sure,
Let me do this
