### ISSUE TITLE
GPRS connection problems

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/emonpi#6]
GPRS should try to re establish connection if there connection issue.

If PPP is not there it should try to bring it up.

**Comment by Basazababo** [comment]
Currently,  it reconnect after five hours while it get new gprs signal strength

**Comment by Basazababo** [comment]
@Alp, are you going to fix it?

**Comment by jlark** [comment]
I'll take a look at this. I think it should try to reconnect if there is no connection and it should still try to update the signal only 5 hours.
