### ISSUE TITLE
make long push on RMC button do a reboot instead of shutdown

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/emonpi#9]
Current function isn't very useful as it's not easy to turn the RMC back on.
instead of a shutdown command we can simply run the reboot command.

**Comment by Basazababo** [comment]
That`s true,
It needs to unplug and plug again to bring it back ON.

**Comment by jlark** [comment]
Perhaps we can have @Britnell do this so he can learn a bit of the ins and outs.
